services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    env_file: .env
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${DB_CONTAINER_NAME}
        POSTGRES_PORT: ${POSTGRES_PORT}
        JWT_SECRET: ${JWT_SECRET}
        JWT_TOKEN_EXPIRE: ${JWT_TOKEN_EXPIRE}
        JWT_REFRESH_TOKEN_EXPIRE: ${JWT_REFRESH_TOKEN_EXPIRE}
        PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./certs:/app/certs:ro
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost:${PORT}/ || wget --no-verbose --tries=1 --spider http://localhost:${PORT}/ || exit 1",
        ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 30s
    stdin_open: true
    tty: true

  postgres:
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - medicine_bank_dev_db:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER} -p ${POSTGRES_PORT}",
        ]
      interval: 1s
      timeout: 5s
      retries: 10

  ui:
    container_name: ${UI_CONTAINER_NAME}
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        UI_PORT: ${UI_PORT}
        API_PORT: ${PORT}
        API_HOST: localhost
        USE_HTTPS: ${USE_HTTPS}

    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./certs:/app/certs:ro
    ports:
      - ${UI_PORT}:${UI_PORT}
    depends_on:
      app:
        condition: service_healthy
      postgres:
        condition: service_healthy

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f vite || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  medicine_bank_dev_db:
