services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    env_file: .env.prod
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${DB_CONTAINER_NAME}
        POSTGRES_PORT: ${POSTGRES_PORT}
        JWT_SECRET: ${JWT_SECRET}
        JWT_TOKEN_EXPIRE: ${JWT_TOKEN_EXPIRE}
        JWT_REFRESH_TOKEN_EXPIRE: ${JWT_REFRESH_TOKEN_EXPIRE}
        PORT: ${PORT}
        USE_HTTPS: ${USE_HTTPS}
        SSL_CERT_PATH: ${SSL_CERT_PATH}
        SSL_KEY_PATH: ${SSL_KEY_PATH}
    volumes:
      - ./certs:/app/certs:ro
      - ./backend/public/audio:/app/public/audio
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost:${PORT}/api/ping || wget --no-verbose --tries=1 --spider http://localhost:${PORT}/api/ping || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    stdin_open: true
    tty: true

  postgres:
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env.prod
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - medicine_bank_prod_db:/var/lib/postgresql/data

  ui:
    container_name: ${UI_CONTAINER_NAME}
    env_file: .env.prod
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        UI_PORT: ${UI_PORT}
        API_PORT: ${PORT}
        API_HOST: ${SERVER_NAME}
        USE_HTTPS: ${USE_HTTPS}
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - UI_PORT=${UI_PORT}
    volumes:
      - ./certs:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "${UI_PORT}:${UI_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost:${UI_PORT}/ || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  medicine_bank_prod_db:
